services:
  fastzero_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"

  fastzero_app:
    image: fastzero_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastzero_database
    env_file:
      - .env

volumes:
  pgdata: